<?php
/**
 * User
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SomeonesComputer\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * someones.computer API
 *
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SomeonesComputer\Sdk\Model;

use \ArrayAccess;
use \SomeonesComputer\Sdk\ObjectSerializer;

/**
 * User Class Doc Comment
 *
 * @category Class
 * @package  SomeonesComputer\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class User implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'User';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'email' => 'string',
        'username' => 'string',
        'display_name' => 'string',
        'theme' => 'string',
        'locale' => 'string',
        'timezone' => 'string',
        'password' => 'string',
        'ldap_dn' => 'string',
        'avatar_photo' => '\SomeonesComputer\Sdk\Model\UserAvatarPhoto',
        'roles' => 'string[]',
        'disabled_at' => '\DateTime',
        'spam_marked_at' => '\DateTime',
        'spam_marked_by' => '\SomeonesComputer\Sdk\Model\User',
        'approved_at' => '\DateTime',
        'email_confirmed_at' => '\DateTime',
        'credit_granted_at' => '\DateTime',
        'tier_pin' => 'string',
        'tier_pinned_at' => '\DateTime',
        'tier_pinned_by' => '\SomeonesComputer\Sdk\Model\User',
        'tier_pin_reason' => 'string',
        'memberships' => '\SomeonesComputer\Sdk\Model\Membership[]',
        'oauth_identities' => '\SomeonesComputer\Sdk\Model\OAuthIdentity[]',
        'totp_secret' => 'string',
        'totp_secret_key_id' => 'string',
        'totp_confirmed_at' => '\DateTime',
        'recovery_codes' => '\SomeonesComputer\Sdk\Model\RecoveryCode[]',
        'machine_for' => 'string',
        'id' => 'string',
        'deleted_at' => '\DateTime',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'display_label' => 'string',
        'machine' => 'bool',
        'ldap_managed' => 'bool',
        'avatar_photo_type' => 'string',
        'user_identifier' => 'string',
        'granted_roles' => 'string[]',
        'disabled' => 'bool',
        'spam' => 'bool',
        'approved' => 'bool',
        'email_confirmed' => 'bool',
        'tier_pinned' => 'bool',
        'totp_enabled' => 'bool',
        'deleted' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'email' => null,
        'username' => null,
        'display_name' => null,
        'theme' => null,
        'locale' => null,
        'timezone' => null,
        'password' => null,
        'ldap_dn' => null,
        'avatar_photo' => null,
        'roles' => null,
        'disabled_at' => 'date-time',
        'spam_marked_at' => 'date-time',
        'spam_marked_by' => null,
        'approved_at' => 'date-time',
        'email_confirmed_at' => 'date-time',
        'credit_granted_at' => 'date-time',
        'tier_pin' => null,
        'tier_pinned_at' => 'date-time',
        'tier_pinned_by' => null,
        'tier_pin_reason' => null,
        'memberships' => null,
        'oauth_identities' => null,
        'totp_secret' => null,
        'totp_secret_key_id' => null,
        'totp_confirmed_at' => 'date-time',
        'recovery_codes' => null,
        'machine_for' => 'iri-reference',
        'id' => 'uuid',
        'deleted_at' => 'date-time',
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'display_label' => null,
        'machine' => null,
        'ldap_managed' => null,
        'avatar_photo_type' => null,
        'user_identifier' => null,
        'granted_roles' => null,
        'disabled' => null,
        'spam' => null,
        'approved' => null,
        'email_confirmed' => null,
        'tier_pinned' => null,
        'totp_enabled' => null,
        'deleted' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'email' => false,
        'username' => false,
        'display_name' => true,
        'theme' => true,
        'locale' => true,
        'timezone' => true,
        'password' => true,
        'ldap_dn' => true,
        'avatar_photo' => true,
        'roles' => false,
        'disabled_at' => true,
        'spam_marked_at' => true,
        'spam_marked_by' => true,
        'approved_at' => true,
        'email_confirmed_at' => true,
        'credit_granted_at' => true,
        'tier_pin' => true,
        'tier_pinned_at' => true,
        'tier_pinned_by' => true,
        'tier_pin_reason' => true,
        'memberships' => false,
        'oauth_identities' => false,
        'totp_secret' => true,
        'totp_secret_key_id' => true,
        'totp_confirmed_at' => true,
        'recovery_codes' => false,
        'machine_for' => true,
        'id' => false,
        'deleted_at' => true,
        'created_at' => false,
        'updated_at' => true,
        'display_label' => false,
        'machine' => false,
        'ldap_managed' => false,
        'avatar_photo_type' => true,
        'user_identifier' => false,
        'granted_roles' => false,
        'disabled' => false,
        'spam' => false,
        'approved' => false,
        'email_confirmed' => false,
        'tier_pinned' => false,
        'totp_enabled' => false,
        'deleted' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'email' => 'email',
        'username' => 'username',
        'display_name' => 'displayName',
        'theme' => 'theme',
        'locale' => 'locale',
        'timezone' => 'timezone',
        'password' => 'password',
        'ldap_dn' => 'ldapDn',
        'avatar_photo' => 'avatarPhoto',
        'roles' => 'roles',
        'disabled_at' => 'disabledAt',
        'spam_marked_at' => 'spamMarkedAt',
        'spam_marked_by' => 'spamMarkedBy',
        'approved_at' => 'approvedAt',
        'email_confirmed_at' => 'emailConfirmedAt',
        'credit_granted_at' => 'creditGrantedAt',
        'tier_pin' => 'tierPin',
        'tier_pinned_at' => 'tierPinnedAt',
        'tier_pinned_by' => 'tierPinnedBy',
        'tier_pin_reason' => 'tierPinReason',
        'memberships' => 'memberships',
        'oauth_identities' => 'oauthIdentities',
        'totp_secret' => 'totpSecret',
        'totp_secret_key_id' => 'totpSecretKeyId',
        'totp_confirmed_at' => 'totpConfirmedAt',
        'recovery_codes' => 'recoveryCodes',
        'machine_for' => 'machineFor',
        'id' => 'id',
        'deleted_at' => 'deletedAt',
        'created_at' => 'createdAt',
        'updated_at' => 'updatedAt',
        'display_label' => 'displayLabel',
        'machine' => 'machine',
        'ldap_managed' => 'ldapManaged',
        'avatar_photo_type' => 'avatarPhotoType',
        'user_identifier' => 'userIdentifier',
        'granted_roles' => 'grantedRoles',
        'disabled' => 'disabled',
        'spam' => 'spam',
        'approved' => 'approved',
        'email_confirmed' => 'emailConfirmed',
        'tier_pinned' => 'tierPinned',
        'totp_enabled' => 'totpEnabled',
        'deleted' => 'deleted'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'email' => 'setEmail',
        'username' => 'setUsername',
        'display_name' => 'setDisplayName',
        'theme' => 'setTheme',
        'locale' => 'setLocale',
        'timezone' => 'setTimezone',
        'password' => 'setPassword',
        'ldap_dn' => 'setLdapDn',
        'avatar_photo' => 'setAvatarPhoto',
        'roles' => 'setRoles',
        'disabled_at' => 'setDisabledAt',
        'spam_marked_at' => 'setSpamMarkedAt',
        'spam_marked_by' => 'setSpamMarkedBy',
        'approved_at' => 'setApprovedAt',
        'email_confirmed_at' => 'setEmailConfirmedAt',
        'credit_granted_at' => 'setCreditGrantedAt',
        'tier_pin' => 'setTierPin',
        'tier_pinned_at' => 'setTierPinnedAt',
        'tier_pinned_by' => 'setTierPinnedBy',
        'tier_pin_reason' => 'setTierPinReason',
        'memberships' => 'setMemberships',
        'oauth_identities' => 'setOauthIdentities',
        'totp_secret' => 'setTotpSecret',
        'totp_secret_key_id' => 'setTotpSecretKeyId',
        'totp_confirmed_at' => 'setTotpConfirmedAt',
        'recovery_codes' => 'setRecoveryCodes',
        'machine_for' => 'setMachineFor',
        'id' => 'setId',
        'deleted_at' => 'setDeletedAt',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'display_label' => 'setDisplayLabel',
        'machine' => 'setMachine',
        'ldap_managed' => 'setLdapManaged',
        'avatar_photo_type' => 'setAvatarPhotoType',
        'user_identifier' => 'setUserIdentifier',
        'granted_roles' => 'setGrantedRoles',
        'disabled' => 'setDisabled',
        'spam' => 'setSpam',
        'approved' => 'setApproved',
        'email_confirmed' => 'setEmailConfirmed',
        'tier_pinned' => 'setTierPinned',
        'totp_enabled' => 'setTotpEnabled',
        'deleted' => 'setDeleted'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'email' => 'getEmail',
        'username' => 'getUsername',
        'display_name' => 'getDisplayName',
        'theme' => 'getTheme',
        'locale' => 'getLocale',
        'timezone' => 'getTimezone',
        'password' => 'getPassword',
        'ldap_dn' => 'getLdapDn',
        'avatar_photo' => 'getAvatarPhoto',
        'roles' => 'getRoles',
        'disabled_at' => 'getDisabledAt',
        'spam_marked_at' => 'getSpamMarkedAt',
        'spam_marked_by' => 'getSpamMarkedBy',
        'approved_at' => 'getApprovedAt',
        'email_confirmed_at' => 'getEmailConfirmedAt',
        'credit_granted_at' => 'getCreditGrantedAt',
        'tier_pin' => 'getTierPin',
        'tier_pinned_at' => 'getTierPinnedAt',
        'tier_pinned_by' => 'getTierPinnedBy',
        'tier_pin_reason' => 'getTierPinReason',
        'memberships' => 'getMemberships',
        'oauth_identities' => 'getOauthIdentities',
        'totp_secret' => 'getTotpSecret',
        'totp_secret_key_id' => 'getTotpSecretKeyId',
        'totp_confirmed_at' => 'getTotpConfirmedAt',
        'recovery_codes' => 'getRecoveryCodes',
        'machine_for' => 'getMachineFor',
        'id' => 'getId',
        'deleted_at' => 'getDeletedAt',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'display_label' => 'getDisplayLabel',
        'machine' => 'getMachine',
        'ldap_managed' => 'getLdapManaged',
        'avatar_photo_type' => 'getAvatarPhotoType',
        'user_identifier' => 'getUserIdentifier',
        'granted_roles' => 'getGrantedRoles',
        'disabled' => 'getDisabled',
        'spam' => 'getSpam',
        'approved' => 'getApproved',
        'email_confirmed' => 'getEmailConfirmed',
        'tier_pinned' => 'getTierPinned',
        'totp_enabled' => 'getTotpEnabled',
        'deleted' => 'getDeleted'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const THEME_HOUSE = 'house';
    public const THEME_CORPORATE = 'corporate';
    public const THEME_DULL = 'dull';
    public const THEME_PLAIN = 'plain';
    public const THEME_RED_LABEL = 'red-label';
    public const LOCALE_EN_GB = 'en_GB';
    public const LOCALE_EN_US = 'en_US';
    public const TIER_PIN_UNTRUSTED = 'untrusted';
    public const TIER_PIN_TRUSTED = 'trusted';
    public const TIER_PIN_VERIFIED = 'verified';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getThemeAllowableValues()
    {
        return [
            self::THEME_HOUSE,
            self::THEME_CORPORATE,
            self::THEME_DULL,
            self::THEME_PLAIN,
            self::THEME_RED_LABEL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLocaleAllowableValues()
    {
        return [
            self::LOCALE_EN_GB,
            self::LOCALE_EN_US,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTierPinAllowableValues()
    {
        return [
            self::TIER_PIN_UNTRUSTED,
            self::TIER_PIN_TRUSTED,
            self::TIER_PIN_VERIFIED,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('username', $data ?? [], null);
        $this->setIfExists('display_name', $data ?? [], null);
        $this->setIfExists('theme', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('timezone', $data ?? [], null);
        $this->setIfExists('password', $data ?? [], null);
        $this->setIfExists('ldap_dn', $data ?? [], null);
        $this->setIfExists('avatar_photo', $data ?? [], null);
        $this->setIfExists('roles', $data ?? [], null);
        $this->setIfExists('disabled_at', $data ?? [], null);
        $this->setIfExists('spam_marked_at', $data ?? [], null);
        $this->setIfExists('spam_marked_by', $data ?? [], null);
        $this->setIfExists('approved_at', $data ?? [], null);
        $this->setIfExists('email_confirmed_at', $data ?? [], null);
        $this->setIfExists('credit_granted_at', $data ?? [], null);
        $this->setIfExists('tier_pin', $data ?? [], null);
        $this->setIfExists('tier_pinned_at', $data ?? [], null);
        $this->setIfExists('tier_pinned_by', $data ?? [], null);
        $this->setIfExists('tier_pin_reason', $data ?? [], null);
        $this->setIfExists('memberships', $data ?? [], null);
        $this->setIfExists('oauth_identities', $data ?? [], null);
        $this->setIfExists('totp_secret', $data ?? [], null);
        $this->setIfExists('totp_secret_key_id', $data ?? [], null);
        $this->setIfExists('totp_confirmed_at', $data ?? [], null);
        $this->setIfExists('recovery_codes', $data ?? [], null);
        $this->setIfExists('machine_for', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('deleted_at', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('display_label', $data ?? [], null);
        $this->setIfExists('machine', $data ?? [], null);
        $this->setIfExists('ldap_managed', $data ?? [], null);
        $this->setIfExists('avatar_photo_type', $data ?? [], null);
        $this->setIfExists('user_identifier', $data ?? [], null);
        $this->setIfExists('granted_roles', $data ?? [], null);
        $this->setIfExists('disabled', $data ?? [], null);
        $this->setIfExists('spam', $data ?? [], null);
        $this->setIfExists('approved', $data ?? [], null);
        $this->setIfExists('email_confirmed', $data ?? [], null);
        $this->setIfExists('tier_pinned', $data ?? [], null);
        $this->setIfExists('totp_enabled', $data ?? [], null);
        $this->setIfExists('deleted', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getThemeAllowableValues();
        if (!is_null($this->container['theme']) && !in_array($this->container['theme'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'theme', must be one of '%s'",
                $this->container['theme'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLocaleAllowableValues();
        if (!is_null($this->container['locale']) && !in_array($this->container['locale'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'locale', must be one of '%s'",
                $this->container['locale'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTierPinAllowableValues();
        if (!is_null($this->container['tier_pin']) && !in_array($this->container['tier_pin'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'tier_pin', must be one of '%s'",
                $this->container['tier_pin'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets email
     *
     * @return string|null
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string|null $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets username
     *
     * @return string|null
     */
    public function getUsername()
    {
        return $this->container['username'];
    }

    /**
     * Sets username
     *
     * @param string|null $username Handle the user can sign in with instead of their email.
     *
     * @return self
     */
    public function setUsername($username)
    {
        if (is_null($username)) {
            throw new \InvalidArgumentException('non-nullable username cannot be null');
        }
        $this->container['username'] = $username;

        return $this;
    }

    /**
     * Gets display_name
     *
     * @return string|null
     */
    public function getDisplayName()
    {
        return $this->container['display_name'];
    }

    /**
     * Sets display_name
     *
     * @param string|null $display_name display_name
     *
     * @return self
     */
    public function setDisplayName($display_name)
    {
        if (is_null($display_name)) {
            array_push($this->openAPINullablesSetToNull, 'display_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('display_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['display_name'] = $display_name;

        return $this;
    }

    /**
     * Gets theme
     *
     * @return string|null
     */
    public function getTheme()
    {
        return $this->container['theme'];
    }

    /**
     * Sets theme
     *
     * @param string|null $theme Which skin this person prefers, or null to take whatever their organization or the instance says.
     *
     * @return self
     */
    public function setTheme($theme)
    {
        if (is_null($theme)) {
            array_push($this->openAPINullablesSetToNull, 'theme');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('theme', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getThemeAllowableValues();
        if (!is_null($theme) && !in_array($theme, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'theme', must be one of '%s'",
                    $theme,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['theme'] = $theme;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string|null $locale Which locale this person prefers, or null for no explicit choice — the same shape as {@see self::$theme}: null is not `en_GB`, it is \"let the cascade decide\" (cookie, then `Accept-Language`, then the instance default). See {@see \\App\\Service\\LocaleResolver} and docs/internationalization.md.
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            array_push($this->openAPINullablesSetToNull, 'locale');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('locale', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getLocaleAllowableValues();
        if (!is_null($locale) && !in_array($locale, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'locale', must be one of '%s'",
                    $locale,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets timezone
     *
     * @return string|null
     */
    public function getTimezone()
    {
        return $this->container['timezone'];
    }

    /**
     * Sets timezone
     *
     * @param string|null $timezone The IANA timezone identifier (e.g. `Europe/London`) this person prefers, or null for no explicit choice — the same shape as {@see self::$locale}: null is not UTC, it is \"let the cascade decide\" (cookie written by the browser's own auto-detection, then the instance default). A plain validated string rather than a backed enum like {@see self::$theme}/{@see self::$locale}: the IANA database has ~400 identifiers, too many for an enum to curate the way {@see \\App\\Enum\\Locale} deliberately does for its two cases. See {@see \\App\\Service\\TimezoneResolver}.
     *
     * @return self
     */
    public function setTimezone($timezone)
    {
        if (is_null($timezone)) {
            array_push($this->openAPINullablesSetToNull, 'timezone');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('timezone', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['timezone'] = $timezone;

        return $this;
    }

    /**
     * Gets password
     *
     * @return string|null
     */
    public function getPassword()
    {
        return $this->container['password'];
    }

    /**
     * Sets password
     *
     * @param string|null $password Hashed password; null for accounts that authenticate only via OAuth or LDAP.
     *
     * @return self
     */
    public function setPassword($password)
    {
        if (is_null($password)) {
            array_push($this->openAPINullablesSetToNull, 'password');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('password', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['password'] = $password;

        return $this;
    }

    /**
     * Gets ldap_dn
     *
     * @return string|null
     */
    public function getLdapDn()
    {
        return $this->container['ldap_dn'];
    }

    /**
     * Sets ldap_dn
     *
     * @param string|null $ldap_dn The bound entry's distinguished name in LLDAP. Presence means the account is LDAP-authoritative: {@see App\\Service\\LdapAccountLinker} clears any local password when it sets this, and it is never set alongside one.
     *
     * @return self
     */
    public function setLdapDn($ldap_dn)
    {
        if (is_null($ldap_dn)) {
            array_push($this->openAPINullablesSetToNull, 'ldap_dn');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('ldap_dn', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['ldap_dn'] = $ldap_dn;

        return $this;
    }

    /**
     * Gets avatar_photo
     *
     * @return \SomeonesComputer\Sdk\Model\UserAvatarPhoto|null
     */
    public function getAvatarPhoto()
    {
        return $this->container['avatar_photo'];
    }

    /**
     * Sets avatar_photo
     *
     * @param \SomeonesComputer\Sdk\Model\UserAvatarPhoto|null $avatar_photo avatar_photo
     *
     * @return self
     */
    public function setAvatarPhoto($avatar_photo)
    {
        if (is_null($avatar_photo)) {
            array_push($this->openAPINullablesSetToNull, 'avatar_photo');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avatar_photo', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['avatar_photo'] = $avatar_photo;

        return $this;
    }

    /**
     * Gets roles
     *
     * @return string[]|null
     */
    public function getRoles()
    {
        return $this->container['roles'];
    }

    /**
     * Sets roles
     *
     * @param string[]|null $roles roles
     *
     * @return self
     */
    public function setRoles($roles)
    {
        if (is_null($roles)) {
            throw new \InvalidArgumentException('non-nullable roles cannot be null');
        }
        $this->container['roles'] = $roles;

        return $this;
    }

    /**
     * Gets disabled_at
     *
     * @return \DateTime|null
     */
    public function getDisabledAt()
    {
        return $this->container['disabled_at'];
    }

    /**
     * Sets disabled_at
     *
     * @param \DateTime|null $disabled_at Set when a platform operator suspends the account; null = active.
     *
     * @return self
     */
    public function setDisabledAt($disabled_at)
    {
        if (is_null($disabled_at)) {
            array_push($this->openAPINullablesSetToNull, 'disabled_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('disabled_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['disabled_at'] = $disabled_at;

        return $this;
    }

    /**
     * Gets spam_marked_at
     *
     * @return \DateTime|null
     */
    public function getSpamMarkedAt()
    {
        return $this->container['spam_marked_at'];
    }

    /**
     * Sets spam_marked_at
     *
     * @param \DateTime|null $spam_marked_at When an operator judged this account to be spam; null = not spam.
     *
     * @return self
     */
    public function setSpamMarkedAt($spam_marked_at)
    {
        if (is_null($spam_marked_at)) {
            array_push($this->openAPINullablesSetToNull, 'spam_marked_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('spam_marked_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['spam_marked_at'] = $spam_marked_at;

        return $this;
    }

    /**
     * Gets spam_marked_by
     *
     * @return \SomeonesComputer\Sdk\Model\User|null
     */
    public function getSpamMarkedBy()
    {
        return $this->container['spam_marked_by'];
    }

    /**
     * Sets spam_marked_by
     *
     * @param \SomeonesComputer\Sdk\Model\User|null $spam_marked_by spam_marked_by
     *
     * @return self
     */
    public function setSpamMarkedBy($spam_marked_by)
    {
        if (is_null($spam_marked_by)) {
            array_push($this->openAPINullablesSetToNull, 'spam_marked_by');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('spam_marked_by', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['spam_marked_by'] = $spam_marked_by;

        return $this;
    }

    /**
     * Gets approved_at
     *
     * @return \DateTime|null
     */
    public function getApprovedAt()
    {
        return $this->container['approved_at'];
    }

    /**
     * Sets approved_at
     *
     * @param \DateTime|null $approved_at When an operator approved the account; null means it is still waiting and can reach nothing but the holding page ({@see self::getRoles()}).
     *
     * @return self
     */
    public function setApprovedAt($approved_at)
    {
        if (is_null($approved_at)) {
            array_push($this->openAPINullablesSetToNull, 'approved_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('approved_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['approved_at'] = $approved_at;

        return $this;
    }

    /**
     * Gets email_confirmed_at
     *
     * @return \DateTime|null
     */
    public function getEmailConfirmedAt()
    {
        return $this->container['email_confirmed_at'];
    }

    /**
     * Sets email_confirmed_at
     *
     * @param \DateTime|null $email_confirmed_at When the address on this account was proven to be one the person can read; null means it never was ({@see \\App\\Service\\EmailConfirmationService}).
     *
     * @return self
     */
    public function setEmailConfirmedAt($email_confirmed_at)
    {
        if (is_null($email_confirmed_at)) {
            array_push($this->openAPINullablesSetToNull, 'email_confirmed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('email_confirmed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['email_confirmed_at'] = $email_confirmed_at;

        return $this;
    }

    /**
     * Gets credit_granted_at
     *
     * @return \DateTime|null
     */
    public function getCreditGrantedAt()
    {
        return $this->container['credit_granted_at'];
    }

    /**
     * Sets credit_granted_at
     *
     * @param \DateTime|null $credit_granted_at When the one-off signup credit was granted ({@see \\App\\Service\\Credit\\SignupGrant}).
     *
     * @return self
     */
    public function setCreditGrantedAt($credit_granted_at)
    {
        if (is_null($credit_granted_at)) {
            array_push($this->openAPINullablesSetToNull, 'credit_granted_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('credit_granted_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['credit_granted_at'] = $credit_granted_at;

        return $this;
    }

    /**
     * Gets tier_pin
     *
     * @return string|null
     */
    public function getTierPin()
    {
        return $this->container['tier_pin'];
    }

    /**
     * Sets tier_pin
     *
     * @param string|null $tier_pin An operator's override of the trust tier this account would otherwise progress into on its own; null means the automatic rule decides ({@see \\App\\Service\\Trust\\TierResolver}).
     *
     * @return self
     */
    public function setTierPin($tier_pin)
    {
        if (is_null($tier_pin)) {
            array_push($this->openAPINullablesSetToNull, 'tier_pin');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tier_pin', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getTierPinAllowableValues();
        if (!is_null($tier_pin) && !in_array($tier_pin, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'tier_pin', must be one of '%s'",
                    $tier_pin,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['tier_pin'] = $tier_pin;

        return $this;
    }

    /**
     * Gets tier_pinned_at
     *
     * @return \DateTime|null
     */
    public function getTierPinnedAt()
    {
        return $this->container['tier_pinned_at'];
    }

    /**
     * Sets tier_pinned_at
     *
     * @param \DateTime|null $tier_pinned_at tier_pinned_at
     *
     * @return self
     */
    public function setTierPinnedAt($tier_pinned_at)
    {
        if (is_null($tier_pinned_at)) {
            array_push($this->openAPINullablesSetToNull, 'tier_pinned_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tier_pinned_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tier_pinned_at'] = $tier_pinned_at;

        return $this;
    }

    /**
     * Gets tier_pinned_by
     *
     * @return \SomeonesComputer\Sdk\Model\User|null
     */
    public function getTierPinnedBy()
    {
        return $this->container['tier_pinned_by'];
    }

    /**
     * Sets tier_pinned_by
     *
     * @param \SomeonesComputer\Sdk\Model\User|null $tier_pinned_by tier_pinned_by
     *
     * @return self
     */
    public function setTierPinnedBy($tier_pinned_by)
    {
        if (is_null($tier_pinned_by)) {
            array_push($this->openAPINullablesSetToNull, 'tier_pinned_by');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tier_pinned_by', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tier_pinned_by'] = $tier_pinned_by;

        return $this;
    }

    /**
     * Gets tier_pin_reason
     *
     * @return string|null
     */
    public function getTierPinReason()
    {
        return $this->container['tier_pin_reason'];
    }

    /**
     * Sets tier_pin_reason
     *
     * @param string|null $tier_pin_reason tier_pin_reason
     *
     * @return self
     */
    public function setTierPinReason($tier_pin_reason)
    {
        if (is_null($tier_pin_reason)) {
            array_push($this->openAPINullablesSetToNull, 'tier_pin_reason');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tier_pin_reason', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['tier_pin_reason'] = $tier_pin_reason;

        return $this;
    }

    /**
     * Gets memberships
     *
     * @return \SomeonesComputer\Sdk\Model\Membership[]|null
     */
    public function getMemberships()
    {
        return $this->container['memberships'];
    }

    /**
     * Sets memberships
     *
     * @param \SomeonesComputer\Sdk\Model\Membership[]|null $memberships memberships
     *
     * @return self
     */
    public function setMemberships($memberships)
    {
        if (is_null($memberships)) {
            throw new \InvalidArgumentException('non-nullable memberships cannot be null');
        }
        $this->container['memberships'] = $memberships;

        return $this;
    }

    /**
     * Gets oauth_identities
     *
     * @return \SomeonesComputer\Sdk\Model\OAuthIdentity[]|null
     */
    public function getOauthIdentities()
    {
        return $this->container['oauth_identities'];
    }

    /**
     * Sets oauth_identities
     *
     * @param \SomeonesComputer\Sdk\Model\OAuthIdentity[]|null $oauth_identities oauth_identities
     *
     * @return self
     */
    public function setOauthIdentities($oauth_identities)
    {
        if (is_null($oauth_identities)) {
            throw new \InvalidArgumentException('non-nullable oauth_identities cannot be null');
        }
        $this->container['oauth_identities'] = $oauth_identities;

        return $this;
    }

    /**
     * Gets totp_secret
     *
     * @return string|null
     */
    public function getTotpSecret()
    {
        return $this->container['totp_secret'];
    }

    /**
     * Sets totp_secret
     *
     * @param string|null $totp_secret The TOTP shared secret, **encrypted at rest** ({@see \\App\\Service\\TwoFactor\\TotpSecretCipher}), or null for an account that has not enabled a second factor.
     *
     * @return self
     */
    public function setTotpSecret($totp_secret)
    {
        if (is_null($totp_secret)) {
            array_push($this->openAPINullablesSetToNull, 'totp_secret');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('totp_secret', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['totp_secret'] = $totp_secret;

        return $this;
    }

    /**
     * Gets totp_secret_key_id
     *
     * @return string|null
     */
    public function getTotpSecretKeyId()
    {
        return $this->container['totp_secret_key_id'];
    }

    /**
     * Sets totp_secret_key_id
     *
     * @param string|null $totp_secret_key_id Which key wrapped {@see self::$totpSecret}, so a key rotation can re-wrap it without users re-enrolling ({@see \\App\\Service\\TwoFactor\\TotpSecretCipher}).
     *
     * @return self
     */
    public function setTotpSecretKeyId($totp_secret_key_id)
    {
        if (is_null($totp_secret_key_id)) {
            array_push($this->openAPINullablesSetToNull, 'totp_secret_key_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('totp_secret_key_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['totp_secret_key_id'] = $totp_secret_key_id;

        return $this;
    }

    /**
     * Gets totp_confirmed_at
     *
     * @return \DateTime|null
     */
    public function getTotpConfirmedAt()
    {
        return $this->container['totp_confirmed_at'];
    }

    /**
     * Sets totp_confirmed_at
     *
     * @param \DateTime|null $totp_confirmed_at When the person proved the authenticator by entering a live code; null means 2FA is not in force for this account. This is the flag the step-up gate reads ({@see \\App\\EventSubscriber\\TwoFactorStepUpSubscriber}).
     *
     * @return self
     */
    public function setTotpConfirmedAt($totp_confirmed_at)
    {
        if (is_null($totp_confirmed_at)) {
            array_push($this->openAPINullablesSetToNull, 'totp_confirmed_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('totp_confirmed_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['totp_confirmed_at'] = $totp_confirmed_at;

        return $this;
    }

    /**
     * Gets recovery_codes
     *
     * @return \SomeonesComputer\Sdk\Model\RecoveryCode[]|null
     */
    public function getRecoveryCodes()
    {
        return $this->container['recovery_codes'];
    }

    /**
     * Sets recovery_codes
     *
     * @param \SomeonesComputer\Sdk\Model\RecoveryCode[]|null $recovery_codes recovery_codes
     *
     * @return self
     */
    public function setRecoveryCodes($recovery_codes)
    {
        if (is_null($recovery_codes)) {
            throw new \InvalidArgumentException('non-nullable recovery_codes cannot be null');
        }
        $this->container['recovery_codes'] = $recovery_codes;

        return $this;
    }

    /**
     * Gets machine_for
     *
     * @return string|null
     */
    public function getMachineFor()
    {
        return $this->container['machine_for'];
    }

    /**
     * Sets machine_for
     *
     * @param string|null $machine_for The organization this account exists to act for, or null for a person.
     *
     * @return self
     */
    public function setMachineFor($machine_for)
    {
        if (is_null($machine_for)) {
            array_push($this->openAPINullablesSetToNull, 'machine_for');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('machine_for', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['machine_for'] = $machine_for;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets deleted_at
     *
     * @return \DateTime|null
     */
    public function getDeletedAt()
    {
        return $this->container['deleted_at'];
    }

    /**
     * Sets deleted_at
     *
     * @param \DateTime|null $deleted_at deleted_at
     *
     * @return self
     */
    public function setDeletedAt($deleted_at)
    {
        if (is_null($deleted_at)) {
            array_push($this->openAPINullablesSetToNull, 'deleted_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('deleted_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['deleted_at'] = $deleted_at;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            array_push($this->openAPINullablesSetToNull, 'updated_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('updated_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets display_label
     *
     * @return string|null
     */
    public function getDisplayLabel()
    {
        return $this->container['display_label'];
    }

    /**
     * Sets display_label
     *
     * @param string|null $display_label How this person is named in the UI. Registration requires a display name, but an OAuth provider may not share one, so the handle stands in — never the email address, which is not ours to show.
     *
     * @return self
     */
    public function setDisplayLabel($display_label)
    {
        if (is_null($display_label)) {
            throw new \InvalidArgumentException('non-nullable display_label cannot be null');
        }
        $this->container['display_label'] = $display_label;

        return $this;
    }

    /**
     * Gets machine
     *
     * @return bool|null
     */
    public function getMachine()
    {
        return $this->container['machine'];
    }

    /**
     * Sets machine
     *
     * @param bool|null $machine Whether this account is a machine acting for an organization, not a person.
     *
     * @return self
     */
    public function setMachine($machine)
    {
        if (is_null($machine)) {
            throw new \InvalidArgumentException('non-nullable machine cannot be null');
        }
        $this->container['machine'] = $machine;

        return $this;
    }

    /**
     * Gets ldap_managed
     *
     * @return bool|null
     */
    public function getLdapManaged()
    {
        return $this->container['ldap_managed'];
    }

    /**
     * Sets ldap_managed
     *
     * @param bool|null $ldap_managed ldap_managed
     *
     * @return self
     */
    public function setLdapManaged($ldap_managed)
    {
        if (is_null($ldap_managed)) {
            throw new \InvalidArgumentException('non-nullable ldap_managed cannot be null');
        }
        $this->container['ldap_managed'] = $ldap_managed;

        return $this;
    }

    /**
     * Gets avatar_photo_type
     *
     * @return string|null
     */
    public function getAvatarPhotoType()
    {
        return $this->container['avatar_photo_type'];
    }

    /**
     * Sets avatar_photo_type
     *
     * @param string|null $avatar_photo_type avatar_photo_type
     *
     * @return self
     */
    public function setAvatarPhotoType($avatar_photo_type)
    {
        if (is_null($avatar_photo_type)) {
            array_push($this->openAPINullablesSetToNull, 'avatar_photo_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('avatar_photo_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['avatar_photo_type'] = $avatar_photo_type;

        return $this;
    }

    /**
     * Gets user_identifier
     *
     * @return string|null
     */
    public function getUserIdentifier()
    {
        return $this->container['user_identifier'];
    }

    /**
     * Sets user_identifier
     *
     * @param string|null $user_identifier The identifier stored in the session token. Sign-in accepts either the email or the username ({@see UserRepository::loadUserByIdentifier()}); this is the canonical one the token is refreshed from.
     *
     * @return self
     */
    public function setUserIdentifier($user_identifier)
    {
        if (is_null($user_identifier)) {
            throw new \InvalidArgumentException('non-nullable user_identifier cannot be null');
        }
        $this->container['user_identifier'] = $user_identifier;

        return $this;
    }

    /**
     * Gets granted_roles
     *
     * @return string[]|null
     */
    public function getGrantedRoles()
    {
        return $this->container['granted_roles'];
    }

    /**
     * Sets granted_roles
     *
     * @param string[]|null $granted_roles The roles the account actually carries, whether or not it has been approved — what the admin panel shows and what the feature toggles flip.
     *
     * @return self
     */
    public function setGrantedRoles($granted_roles)
    {
        if (is_null($granted_roles)) {
            throw new \InvalidArgumentException('non-nullable granted_roles cannot be null');
        }
        $this->container['granted_roles'] = $granted_roles;

        return $this;
    }

    /**
     * Gets disabled
     *
     * @return bool|null
     */
    public function getDisabled()
    {
        return $this->container['disabled'];
    }

    /**
     * Sets disabled
     *
     * @param bool|null $disabled disabled
     *
     * @return self
     */
    public function setDisabled($disabled)
    {
        if (is_null($disabled)) {
            throw new \InvalidArgumentException('non-nullable disabled cannot be null');
        }
        $this->container['disabled'] = $disabled;

        return $this;
    }

    /**
     * Gets spam
     *
     * @return bool|null
     */
    public function getSpam()
    {
        return $this->container['spam'];
    }

    /**
     * Sets spam
     *
     * @param bool|null $spam spam
     *
     * @return self
     */
    public function setSpam($spam)
    {
        if (is_null($spam)) {
            throw new \InvalidArgumentException('non-nullable spam cannot be null');
        }
        $this->container['spam'] = $spam;

        return $this;
    }

    /**
     * Gets approved
     *
     * @return bool|null
     */
    public function getApproved()
    {
        return $this->container['approved'];
    }

    /**
     * Sets approved
     *
     * @param bool|null $approved approved
     *
     * @return self
     */
    public function setApproved($approved)
    {
        if (is_null($approved)) {
            throw new \InvalidArgumentException('non-nullable approved cannot be null');
        }
        $this->container['approved'] = $approved;

        return $this;
    }

    /**
     * Gets email_confirmed
     *
     * @return bool|null
     */
    public function getEmailConfirmed()
    {
        return $this->container['email_confirmed'];
    }

    /**
     * Sets email_confirmed
     *
     * @param bool|null $email_confirmed email_confirmed
     *
     * @return self
     */
    public function setEmailConfirmed($email_confirmed)
    {
        if (is_null($email_confirmed)) {
            throw new \InvalidArgumentException('non-nullable email_confirmed cannot be null');
        }
        $this->container['email_confirmed'] = $email_confirmed;

        return $this;
    }

    /**
     * Gets tier_pinned
     *
     * @return bool|null
     */
    public function getTierPinned()
    {
        return $this->container['tier_pinned'];
    }

    /**
     * Sets tier_pinned
     *
     * @param bool|null $tier_pinned tier_pinned
     *
     * @return self
     */
    public function setTierPinned($tier_pinned)
    {
        if (is_null($tier_pinned)) {
            throw new \InvalidArgumentException('non-nullable tier_pinned cannot be null');
        }
        $this->container['tier_pinned'] = $tier_pinned;

        return $this;
    }

    /**
     * Gets totp_enabled
     *
     * @return bool|null
     */
    public function getTotpEnabled()
    {
        return $this->container['totp_enabled'];
    }

    /**
     * Sets totp_enabled
     *
     * @param bool|null $totp_enabled True once the person has proved the authenticator — the gate's on/off switch.
     *
     * @return self
     */
    public function setTotpEnabled($totp_enabled)
    {
        if (is_null($totp_enabled)) {
            throw new \InvalidArgumentException('non-nullable totp_enabled cannot be null');
        }
        $this->container['totp_enabled'] = $totp_enabled;

        return $this;
    }

    /**
     * Gets deleted
     *
     * @return bool|null
     */
    public function getDeleted()
    {
        return $this->container['deleted'];
    }

    /**
     * Sets deleted
     *
     * @param bool|null $deleted deleted
     *
     * @return self
     */
    public function setDeleted($deleted)
    {
        if (is_null($deleted)) {
            throw new \InvalidArgumentException('non-nullable deleted cannot be null');
        }
        $this->container['deleted'] = $deleted;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


