<?php
/**
 * CreditTransactionEngineMillisTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SomeonesComputer\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * someones.computer API
 *
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace SomeonesComputer\Sdk\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CreditTransactionEngineMillisTest Class Doc Comment
 *
 * @category    Class
 * @description The engine-milliseconds this load debit was computed from — the delta {@see \\App\\Service\\ManagedService\\LoadSampler} accrued and {@see \\App\\Service\\Credit\\LoadBiller} then billed and cleared. Null on anything but a load debit.
 * @package     SomeonesComputer\Sdk
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CreditTransactionEngineMillisTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CreditTransactionEngineMillis"
     */
    public function testCreditTransactionEngineMillis()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
