<?php
/**
 * AdoptionApprovalApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  SomeonesComputer\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * someones.computer API
 *
 * JSON-LD resources backing the control panel. Bearer-token reachable since #1418 — see docs/sdk-generation.md.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace SomeonesComputer\Sdk\Test\Api;

use \SomeonesComputer\Sdk\Configuration;
use \SomeonesComputer\Sdk\ApiException;
use \SomeonesComputer\Sdk\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AdoptionApprovalApiTest Class Doc Comment
 *
 * @category Class
 * @package  SomeonesComputer\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AdoptionApprovalApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiAdoptionApprovalsGetCollection
     *
     * Retrieves the collection of AdoptionApproval resources..
     *
     */
    public function testApiAdoptionApprovalsGetCollection()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiAdoptionApprovalsIdDelete
     *
     * Removes the AdoptionApproval resource..
     *
     */
    public function testApiAdoptionApprovalsIdDelete()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiAdoptionApprovalsIdGet
     *
     * Retrieves a AdoptionApproval resource..
     *
     */
    public function testApiAdoptionApprovalsIdGet()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiAdoptionApprovalsPost
     *
     * Creates a AdoptionApproval resource..
     *
     */
    public function testApiAdoptionApprovalsPost()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
